# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Package Application'
    steps:
    - script: echo Building the application...
      displayName: 'Start Build Process'

    - script: |
        python --version
        pip install -r requirements.txt
        pip install -e .
      displayName: 'Install Dependencies'

    - script: |
        echo Creating deployment package...
        zip -r $(Build.ArtifactStagingDirectory)/app.zip .
      displayName: 'Package Application'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy Application'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure App Service'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Default Subscription(0f21e802-aeff-4e83-977e-a5bde15f65c1)'
        appType: 'webAppLinux'
        WebAppName: 'agentic-paulch'
        packageForLinux: '$(Pipeline.Workspace)/drop/app.zip'
        RuntimeStack: 'PYTHON|3.11'
        StartupCommand: 'cd src/agentic && panel serve main.py --port $PORT --allow-websocket-origin=* --address=0.0.0.0'